version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary dependencies"
      - apt-get update && apt-get install -y git 

  pre_build:
    commands:
      - echo "Fetching the Personal Access Token from Parameter Store..."
      # Fetching the Personal Access Token and exporting it as an environment variable
      - export GITHUB_TOKEN=$(aws ssm get-parameter --name "PAT-Enterprise" --with-decryption --query "Parameter.Value" --output text)

      - echo "Cloning Community repo...."
      - git clone https://github.com/madhukamath29/demo-odoo17.git community-repo

      - echo "Cloning Enterprise repo..."
      - git clone https://$GITHUB_TOKEN@github.com/Code-with-Maddy/test.git enterprise-repo

      - echo "Cloning Third-party addons from Inv-repo..."
      - git clone --branch Third-party-addon https://github.com/madhukamath29/INV-Repo.git third-party-repo

      - echo "Cloning Common addons from Inv-repo...."
      - git clone --branch common-addon https://github.com/madhukamath29/INV-Repo.git common-addon-repo

      - echo "Cloning GST branch from Inv-repo...."
      - git clone --branch GST-Enterprise --single-branch https://github.com/madhukamath29/INV-Repo.git gst-repo

  build:
    commands:
      - echo "Merging the necessary repositories into the community repo...."
      
      # Merge the Enterprise repo into community repo
      - cp -r enterprise-repo/* community-repo/

      # Copy the third-party addons, common addons, and GST into specific folders inside the community repo
      - mkdir -p community-repo/third-party-addons
      - cp -r third-party-repo/* community-repo/third-party-addons/

      - mkdir -p community-repo/common-addons
      - cp -r common-addon-repo/* community-repo/common-addons/

      - mkdir -p community-repo/gst-addons
      - cp -r gst-repo/* community-repo/gst-addons/  

  post_build:
    commands:
      - echo "Build complete, all repositories merged inside the community repo."

artifacts:
  files:
    - '**/*'  
base-directory: community-repo
